### ISSUE TITLE
Use `coremltools` to generate usable `.mlmodel` from TensorFlow model

### ISSUE THREAD

**Issue by SichangHe** [FedCampus/FedKit#21]
Branch: https://github.com/SichangHe/FedCampus--FedKit/tree/coreml-model

---

Set an optimizer and epochs:
https://github.com/SichangHe/FedCampus--FedKit/commit/d521f00c591e78cec811321772acb65d462115e5
Bug: `Must provide training inputs for updatable neural network (expecting both input and target for loss function)`.
![image](https://github.com/FedCampus/FedKit/assets/84777573/90f749c5-424a-40b0-b736-1121ca1f7580)

---

Add optimizer:
https://github.com/SichangHe/FedCampus--FedKit/commit/254a8c5714f2102191bd821ea440f15e6136a148
Error: `ValueError: Categorical Cross Entropy loss layer input (Identity) must be a softmax layer output.`

---

Patch softmax in `coremltools/converters/mil/frontend/tensorflow/ops.py`:
```diff
  @register_tf_op
  def Softmax(context, node):
      logit = context[node.inputs[0]]
-     axis = node.attr.get("axis")
+     axis = node.attr.get("axis", -3)
      x = mb.softmax(x=logit, axis=axis, name=node.name)
      context.add(node.name, x)
```
Bug: `There is a layer (transpose_6), which does not support backpropagation, between an updatable marked layer and the loss function.
![image](https://github.com/FedCampus/FedKit/assets/84777573/c7c7d659-bc15-420e-8574-6181912f2e40)

---

I cannot get over this bug because such transpose layer is always added between `Conv` and softmax, and `Conv` is the only actual updatable layer we have.

**Comment by SichangHe** [comment]
Maybe it is better done in Swift: https://github.com/JacopoMangiavacchi/MNIST-CoreML-Training#swiftcoremltools-trainable-model

**Comment by SichangHe** [comment]
Switched to mean squared error loss.
https://github.com/SichangHe/FedCampus--FedKit/commit/f12a3dab354c180c759a6b41a5d3080727ce627e
No need to patch `coremltools` any more. But, the last error persists.

**Comment by SichangHe** [comment]
Uploading both MNIST models:

```python
from fed_kit import *
tflite_file = "mnist.tflite"
coreml_file = "mnist.mlmodel"
name = "mnist_unified"
tflite_layers = [1152, 128, 36864, 128, 1600000, 2000, 20000, 40]
coreml_layers = [{'name': 'sequential/conv2d/BiasAdd', 'type': 'weights'}, {'name': 'sequential/conv2d/BiasAdd', 'type': 'bias'}, {'name': 'sequential/conv2d_1/BiasAdd', 'type': 'weights'}, {'name': 'sequential/conv2d_1/BiasAdd', 'type': 'bias'}, {'name': 'sequential/dense/BiasAdd', 'type': 'weights'}, {'name': 'sequential/dense/BiasAdd', 'type': 'bias'}, {'name': 'sequential/dense_1/BiasAdd', 'type': 'weights'}, {'name': 'sequential/dense_1/BiasAdd', 'type': 'bias'}]
data_type = "MNIST_28x28x1"
response = upload(tflite_file, coreml_file, name, tflite_layers, coreml_layers, data_type)
```

**Comment by SichangHe** [comment]
Training this model on iOS simulator produces a SegFault when `GetParameters` is hit.

**Comment by SichangHe** [comment]
`EvaluateIns` does not cause SegFault. But, the `contextProgress.metrics[.lossValue]` is `nil`.

**Comment by SichangHe** [comment]
Changing these causes the old, working MNIST model from Jacopo to SegFault:

https://github.com/FedCampus/FedKit/blob/c657a2b3df0ea20b0f486dd1e82315ddd49d6904/fed_kit_client/ios/Runner/DataLoader.swift#L114-L115

Therefore, I assume that the `MLFeatureValue`s must match the model's input and output for it to not crash.

However, changing it to

```swift
                let dataPointFeatures: [String: MLFeatureValue] = ["conv2d_input": imageValue,
                                                                   "Identity": outputValue]
```

Does not solve the problem, so maybe those are not the actual input/output of the model we generated.
Edit: "Identity_true" "sequential/dense_1/BiasAdd_true", "sequential/dense_1/BiasAdd" do not work neither.

Inspecting the old, working MNIST in Xcode, it seems that these names are under the `Updates` tab. And, the new model has "conv2d_input" and "sequential/dense_1/BiasAdd_true".

**Comment by SichangHe** [comment]
Changing this `[1, 28, 28, 1]` also leads to the old, working example to crash:

https://github.com/FedCampus/FedKit/blob/c657a2b3df0ea20b0f486dd1e82315ddd49d6904/fed_kit_client/ios/Runner/DataLoader.swift#L16

But, it allows the new example to run for one epoch…

**Comment by SichangHe** [comment]
This is what I get by manually adding output shape 10 to the model:

![softmax_error](https://github.com/FedCampus/FedKit/assets/84777573/accc3318-beb8-459a-8b11-4d2430c30858)

@luuvy757, could you see what is up here?

<details><summary>Code used and output.</summary>

```python
In [1]: import coremltools as ct

In [5]: spec = ct.utils.load_spec("mnist.mlmodel")

In [7]: builder = ct.models.neural_network.NeuralNetworkBuilder(spec=spec)

In [8]: builder.inspect_layers()
[Id: 13], Name: sequential/dense_1/Softmax (Type: softmax)
          Updatable: False
          Input blobs: ['sequential/dense_1/BiasAdd']
          Output blobs: ['Identity']
[Id: 12], Name: sequential/dense_1/BiasAdd (Type: innerProduct)
          Updatable: True
          Input blobs: ['sequential/dense/Relu']
          Output blobs: ['sequential/dense_1/BiasAdd']
[Id: 11], Name: sequential/dense/Relu (Type: activation)
          Updatable: False
          Input blobs: ['sequential/dense/BiasAdd']
          Output blobs: ['sequential/dense/Relu']
[Id: 10], Name: sequential/dense/BiasAdd (Type: innerProduct)
          Updatable: True
          Input blobs: ['sequential/flatten/Reshape']
          Output blobs: ['sequential/dense/BiasAdd']
[Id: 9], Name: sequential/flatten/Reshape (Type: reshapeStatic)
          Updatable: False
          Input blobs: ['transpose_8']
          Output blobs: ['sequential/flatten/Reshape']
[Id: 8], Name: transpose_8 (Type: transpose)
          Updatable: False
          Input blobs: ['max_pool_1']
          Output blobs: ['transpose_8']
[Id: 7], Name: max_pool_1 (Type: pooling)
          Updatable: False
          Input blobs: ['sequential/conv2d_1/Relu']
          Output blobs: ['max_pool_1']
[Id: 6], Name: sequential/conv2d_1/Relu (Type: activation)
          Updatable: False
          Input blobs: ['sequential/conv2d_1/BiasAdd']
          Output blobs: ['sequential/conv2d_1/Relu']
[Id: 5], Name: sequential/conv2d_1/BiasAdd (Type: convolution)
          Updatable: False
          Input blobs: ['max_pool_0']
          Output blobs: ['sequential/conv2d_1/BiasAdd']
[Id: 4], Name: max_pool_0 (Type: pooling)
          Updatable: False
          Input blobs: ['sequential/conv2d/Relu']
          Output blobs: ['max_pool_0']
[Id: 3], Name: sequential/conv2d/Relu (Type: activation)
          Updatable: False
          Input blobs: ['sequential/conv2d/BiasAdd']
          Output blobs: ['sequential/conv2d/Relu']
[Id: 2], Name: sequential/conv2d/BiasAdd (Type: convolution)
          Updatable: False
          Input blobs: ['transpose_9']
          Output blobs: ['sequential/conv2d/BiasAdd']
[Id: 1], Name: transpose_9 (Type: transpose)
          Updatable: False
          Input blobs: ['sequential/reshape/Reshape']
          Output blobs: ['transpose_9']
[Id: 0], Name: sequential/reshape/Reshape (Type: reshapeStatic)
          Updatable: False
          Input blobs: ['input_1']
          Output blobs: ['sequential/reshape/Reshape']

In [12]: spec.description
Out[12]:
input {
  name: "input_1"
  type {
    multiArrayType {
      shape: 1
      shape: 28
      shape: 28
      dataType: FLOAT32
      shapeRange {
        sizeRanges {
          lowerBound: 1
          upperBound: -1
        }
        sizeRanges {
          lowerBound: 28
          upperBound: 28
        }
        sizeRanges {
          lowerBound: 28
          upperBound: 28
        }
      }
    }
  }
}
output {
  name: "Identity"
  type {
    multiArrayType {
      dataType: FLOAT32
    }
  }
}
trainingInput {
  name: "input_1"
  type {
    multiArrayType {
      shape: 1
      shape: 28
      shape: 28
      dataType: FLOAT32
      shapeRange {
        sizeRanges {
          lowerBound: 1
          upperBound: -1
        }
        sizeRanges {
          lowerBound: 28
          upperBound: 28
        }
        sizeRanges {
          lowerBound: 28
          upperBound: 28
        }
      }
    }
  }
}
trainingInput {
  name: "Identity_true"
  type {
    multiArrayType {
      shape: 1
      dataType: INT32
    }
  }
}
metadata {
  userDefined {
    key: "com.github.apple.coremltools.source"
    value: "tensorflow==2.13.0"
  }
  userDefined {
    key: "com.github.apple.coremltools.version"
    value: "6.3.0"
  }
}

In [24]: spec.description.output[0].type.multiArrayType.shape.append(10)

In [25]: spec.description
Out[25]:
input {
  name: "input_1"
  type {
    multiArrayType {
      shape: 1
      shape: 28
      shape: 28
      dataType: FLOAT32
      shapeRange {
        sizeRanges {
          lowerBound: 1
          upperBound: -1
        }
        sizeRanges {
          lowerBound: 28
          upperBound: 28
        }
        sizeRanges {
          lowerBound: 28
          upperBound: 28
        }
      }
    }
  }
}
output {
  name: "Identity"
  type {
    multiArrayType {
      shape: 10
      dataType: FLOAT32
    }
  }
}
trainingInput {
  name: "input_1"
  type {
    multiArrayType {
      shape: 1
      shape: 28
      shape: 28
      dataType: FLOAT32
      shapeRange {
        sizeRanges {
          lowerBound: 1
          upperBound: -1
        }
        sizeRanges {
          lowerBound: 28
          upperBound: 28
        }
        sizeRanges {
          lowerBound: 28
          upperBound: 28
        }
      }
    }
  }
}
trainingInput {
  name: "Identity_true"
  type {
    multiArrayType {
      shape: 1
      dataType: INT32
    }
  }
}
metadata {
  userDefined {
    key: "com.github.apple.coremltools.source"
    value: "tensorflow==2.13.0"
  }
  userDefined {
    key: "com.github.apple.coremltools.version"
    value: "6.3.0"
  }
}
```

</details>

**Comment by SHAO-Jiaqi757** [comment]
No idea. Try {shape: 1, shape: 10}? But why need to add shape [10] to the output layer?

**Comment by SichangHe** [comment]
> But why need to add shape [10] to the output layer?

I was just observing the difference between the model we generated with the working model, and that model has `shape` for `output`.

<details><summary>Working model's description.</summary>

```python
In [2]: spec = ct.utils.load_spec("backend/static/MNIST--mnist.mlmodel")

In [3]: spec.description
Out[3]:
input {
  name: "image"
  type {
    multiArrayType {
      shape: 1
      shape: 28
      shape: 28
      dataType: FLOAT32
    }
  }
}
output {
  name: "output"
  type {
    multiArrayType {
      shape: 10
      dataType: FLOAT32
    }
  }
}
trainingInput {
  name: "image"
  type {
    multiArrayType {
      shape: 1
      shape: 28
      shape: 28
      dataType: FLOAT32
    }
  }
}
trainingInput {
  name: "output_true"
  type {
    multiArrayType {
      shape: 1
      dataType: INT32
    }
  }
}
metadata {
  shortDescription: "MNIST-Trainable"
  author: "Jacopo Mangiavacchi"
  license: "MIT"
  userDefined {
    key: "SwiftCoremltoolsVersion"
    value: "0.0.12"
  }
}
```

</details>

**Comment by SichangHe** [comment]
> Try {shape: 1, shape: 10}?

![image](https://github.com/FedCampus/FedKit/assets/84777573/566c3b48-b253-42ea-b143-1b5c857011be)

Okay, well… Maybe [1, 1, 10].

Edit: and then it loads…

Edit: Doesn't matter. Still crashes when training.

**Comment by SichangHe** [comment]
After getting the app to run in Xcode, I get the explanation for the crash:

```python
Runner(53293,0x16f317000) malloc: Incorrect checksum for freed object 0x1688e2000: probably modified after being freed.
Corrupt value: 0xc1980000688f4000
Runner(53293,0x16f317000) malloc: *** set a breakpoint in malloc_error_break to debug
Runner(53293,0x16f317000) malloc: Incorrect checksum for freed object 0x1688e2000: probably modified after being freed.
Corrupt value: 0xc1980000688f4000
CoreSimulator 857.7 - Device: iPhone 14 Pro Max (CB79BDAB-7D81-43FC-8440-FE4B95955A60) - Runtime: iOS 16.0 (20A360) - DeviceType: iPhone 14 Pro Max
```

**Comment by SichangHe** [comment]
To get the app to run in Xcode, open it from `Runner.xcworkspace`.

**Comment by SichangHe** [comment]
Avoiding softmax and cross-entropy loss gives a model that does not crash. However, it produces 0 loss all the time and 100% test accuracy. Edit: @danielnugraha, any ideas why?

[Branch](https://github.com/SichangHe/FedCampus--FedKit/tree/coreml-model-10output).

Also, this gets me to think that the previous 0 loss we see from Jacopo's model was also fake. There must be something wrong.

**Comment by SichangHe** [comment]
I've submitted a ticket to feedbackassistant.apple.com about the crash.

**Comment by SichangHe** [comment]
My current suspicion for the reason for the crash is:
1. I hacked `coremltools` to convert `activation="softmax"` to Core ML's `softmax` instead of `softmaxND`.
2. I made a cross-entropy loss layer whose input is the output of that softmax layer

**Comment by danielnugraha** [comment]
Loss 0 does not mean something wrong, it can be overfitting since the dataset is large.
Try reducing the dataset size and see if it outputs 0 loss.

**Comment by danielnugraha** [comment]
Please check the shape once again, https://coremltools.readme.io/docs/image-inputs.

**Comment by SichangHe** [comment]
I tried a 1% size training set and still got 0 loss. I even cleared the parameters. I will try to generate random parameters to test.

<details><summary>Edit: random parameters did cause non-zero losses. They are a bit crazy, though.</summary>

![image](https://github.com/FedCampus/FedKit/assets/84777573/cbfed296-7c51-492d-978d-ca043c3a04e9)

</details>

**Comment by SichangHe** [comment]
@danielnugraha, for the shape, could you point out where you are referring to?

**Comment by danielnugraha** [comment]
For the model from Jacopo, the shape [10] refers to each of the digit 0-9, where the predicted digit will be set to 1, and other 0. So it really depends on how you design your model.

**Comment by danielnugraha** [comment]
I gave a wrong example, please refer to https://coremltools.readme.io/docs/image-inputs.

**Comment by SichangHe** [comment]
I've already changed the output shape for mean square err to work. https://github.com/SichangHe/FedCampus--FedKit/commit/c816ea5b0b8794ab9485847f1261c1e6dfec2e20#diff-8486e2af36d4ca5bc3154be7d7c89b883a7599f41a04fcf19dd3f4f160f3199c

**Comment by SichangHe** [comment]
I guess the workflow works, then. It is just we cannot use softmax and cross-entropy loss.

**Comment by danielnugraha** [comment]
Which function do you call to get the info for average loss? Seems wrong to me.

**Comment by SichangHe** [comment]
The functions to get the loss is from Flower iOS example.

https://github.com/SichangHe/FedCampus--FedKit/blob/c816ea5b0b8794ab9485847f1261c1e6dfec2e20/fed_kit_client/ios/Runner/Utils/Flwr/MLClient.swift#L68-L73

https://github.com/SichangHe/FedCampus--FedKit/blob/c816ea5b0b8794ab9485847f1261c1e6dfec2e20/fed_kit_client/ios/Runner/Utils/Flwr/MLClient.swift#L94-L95

**Comment by SichangHe** [comment]
From https://github.com/apple/coremltools/issues/1705, it seems that `coremltools`'s softmax is broken for a while. And, https://github.com/apple/coremltools/issues/1714 may be the cause of it.

**Comment by SichangHe** [comment]
Core ML's softmax might be broken as well. I tried [adding the softmax layer manually](https://github.com/SichangHe/FedCampus--FedKit/commit/3a00b9fdb367a25c8d605636d4ec4faf0da3f505), and the resulting model still caused a crash.

<details><summary>Screenshot</summary>

![image](https://github.com/FedCampus/FedKit/assets/84777573/891e323e-a9b5-447f-a7c9-cd4d1b850fe8)

</details>

**Comment by SichangHe** [comment]
This is partially solved by only using mean square error.
