### ISSUE TITLE
Local model update 

### ISSUE THREAD

**Issue by Deepakpy** [FedCampus/FedKit#22]
Once the local Android finishes training does it save the new updates from the server as a tflite file or how do one save the new updates from training on the local Android device to use.

**Comment by SichangHe** [comment]
After each round, the Flower Server sends the parameters, a list of Numpy arrays, to the backend in pickled form.

https://github.com/FedCampus/FedKit/blob/c657a2b3df0ea20b0f486dd1e82315ddd49d6904/backend/train/run.py#L50-L59
