### ISSUE TITLE
Access the backend over proxy

### ISSUE THREAD

**Issue by SichangHe** [FedCampus/FedKit#30]
## The problem

Under DKU Wi-Fi, with proxy set to `auto`, client apps have problem connecting to our backend in the DKU intranet.

Confirmed by @Beilong-Tang on HarmonyOS.

Similar issue when I was testing on iOS. Interestingly, after setting the proxy to `off` and the first request succeeds, subsequent requests continue to succeed with proxy `auto`, presumably due to route caching. 

## Discoveries by @lywlywly

Dart libraries `Dio` and its dependency `Http` do not respect system proxy settings.

I do expect this because these libraries do not have reliable ways to read system settings (side effects). The interesting question is how ignoring proxy messes up the route resolution.

**Comment by lywlywly** [comment]
I cannot reproduce the issue of accessing backend server on my Android phone (OPPO Reno 8). However, sometimes the Android native code getting Huawei Health data does not work behind proxy.
  <details>
  <summary>proxy settings on my phone</summary>
  <img src="https://github.com/FedCampus/FedKit/assets/127578497/42510c4f-a69f-4b31-96df-de0d8aa5b1b2" alt="proxy setting" height=720>
  </details>

Also as implied in this [flutter issue](https://github.com/flutter/flutter/issues/26359), flutter apps do not recognize proxy settings by default.

**Comment by SichangHe** [comment]
Just let the users turn off proxy when using the app…

**Comment by lywlywly** [comment]
When on proxy, I cannot get data of types resting heart rate, intense exercise time, and sleep efficiency from huawei, while other data types are fine. This is really weird though.
